version: '{build}'

cache:
- c:\tools\vcpkg\installed\ -> packages.txt

# We always want 32 and 64-bit compilation
matrix:
  fast_finish: false     # set this flag to immediately finish build once one of the jobs fails.

install:
  - setlocal EnableExtensions EnableDelayedExpansion
  - copy c:\projects\nimbus-deps\triplets\*.* c:\tools\vcpkg\triplets\
build_script:
  - mkdir C:\projects\nimbus-deps\bin
  - mkdir C:\projects\nimbus-deps\bin\x86
  - mkdir C:\projects\nimbus-deps\bin\x64
  - mkdir C:\projects\nimbus-deps\dist
  - vcpkg install snappy:x86-windows-static-crt
  - vcpkg install snappy:x64-windows-static-crt
  - vcpkg install rocksdb[lz4,zlib,snappy]:x86-windows-rocksdb
  - vcpkg install rocksdb[lz4,zlib,snappy]:x64-windows-rocksdb
  - copy c:\tools\vcpkg\installed\x86-windows-static-crt\bin\*.dll C:\projects\nimbus-deps\bin\x86\
  - copy c:\tools\vcpkg\installed\x64-windows-static-crt\bin\*.dll C:\projects\nimbus-deps\bin\x64\
  - copy c:\tools\vcpkg\installed\x86-windows-rocksdb\bin\rocksdb-shared.dll C:\projects\nimbus-deps\bin\x86\librocksdb.dll
  - copy c:\tools\vcpkg\installed\x64-windows-rocksdb\bin\rocksdb-shared.dll C:\projects\nimbus-deps\bin\x64\librocksdb.dll
  - cd c:\projects\nimbus-deps\lmdb
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cl.exe /DLMDBWINDOWSDLL_EXPORTS dllmain.c mdb-dll.c midl-dll.c advapi32.lib /link /DLL /OUT:lmdb32.dll
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cl.exe /DLMDBWINDOWSDLL_EXPORTS dllmain.c mdb-dll.c midl-dll.c advapi32.lib /link /DLL /OUT:lmdb64.dll
  - copy c:\projects\nimbus-deps\lmdb\lmdb32.dll c:\projects\nimbus-deps\bin\x86\lmdb.dll
  - copy c:\projects\nimbus-deps\lmdb\lmdb64.dll c:\projects\nimbus-deps\bin\x64\lmdb.dll
  - 7z a -r C:\projects\nimbus-deps\dist\nimbus-deps.zip C:\projects\nimbus-deps\bin\*.* > nul
  - appveyor PushArtifact C:\projects\nimbus-deps\dist\nimbus-deps.zip
test: off
deploy:
  release: nimbus-deps
  description: 'Nimbus binary dependencies'
  provider: GitHub
  auth_token:
    secure: Zu/JtLX4O5watrgvqG+Hw6mPSepU7mOGm7aOehTwBhwUdI/89Ma+imgYKM+qERXG
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: false
