name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: windows
            cpu: amd64
        include:
          - target:
              os: windows
            builder: windows-2019
            shell: msys2 {0}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: '${{ matrix.target.os }}-${{ matrix.target.cpu }} (Nim ${{ matrix.branch }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install DLL dependencies (Windows)
        if: >
          runner.os == 'Windows'
        run: |
          mkdir bin
          mkdir bin/x86
          mkdir bin/x64
          mkdir dist

          if [[ '${{ matrix.target.cpu }}' == 'amd64' ]]; then
            ROCKSDBSUB=x64
          else
            ROCKSDBSUB=x86
          fi

      - name: Run tests
        run: |
          echo "Done"
